version: "3.8"

services:
    mysql:
        image: mysql:8.0
        restart: always
        volumes:
            - ~/.docker/data/mysqlcmspartner:/var/lib/mysql:rw
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root123
            MYSQL_PASSWORD: 12345678
            MYSQL_USER: admin
            MYSQL_DATABASE: cms-partner
            MYSQL_PORT: 3306
        command:
          [
              "mysqld",
              "--authentication-policy=mysql_native_password",
              "--character-set-server=utf8mb4",
              "--collation-server=utf8mb4_unicode_ci",
          ]

    redis:
        container_name: redis_cm_partner
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ~/.docker/data/rediscmspartnerconf:/redis.conf
            - ~/.docker/data/rediscmspartner:/var/lib/redis
        command: redis-server --requirepass 1234

volumes:
    rediscmspartnerconf:
    rediscmspartner:
    mysqlcmspartner:
